FROM debian:latest
COPY src /usr/bin/src
ENV HOST localhost 
ENV PORT 6379
ENV TASKS 2000
ENV POOLSIZE 200
WORKDIR /usr/bin
RUN apt-get update
RUN apt-get install -y redis
RUN apt-get install -y wget
RUN apt-get install -y unzip
RUN apt-get install -y gcc automake autoconf libtool make
RUN wget https://github.com/redis/hiredis/archive/master.zip
RUN unzip master.zip
WORKDIR /usr/bin/hiredis-master
RUN make
RUN make install
RUN mkdir /usr/lib/hiredis
RUN mkdir /usr/include/hiredis
RUN cp /usr/bin/hiredis-master/libhiredis.so /usr/lib/hiredis
RUN cp /usr/bin/hiredis-master/hiredis.h /usr/include/hiredis
RUN echo '/usr/local/lib' >>/etc/ld.so.conf
RUN ldconfig
WORKDIR /usr/bin/src
RUN gcc net.h shortUrlClient.c -lpthread -lhiredis -o surl_client_2
CMD ./surl_client_2 {$HOST} {$PORT} 0 {$TASKS} {$POOLSIZE}